[versions]
dokka = "1.8.20"
gradlePlugins-versionCatalog = "0.8.0"
kotest = "5.6.2"
kotlin = "1.9.0"
kotlin-html = "0.9.1"
ktlint = "0.48.2"
nexus = "1.3.0"
spotless = "6.19.0"
versions = "0.47.0"

[libraries]
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlin-html" }

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
serialisation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradlePlugins-versionCatalog" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
